name: ğŸ Generate Contribution Snake

on:
  schedule:
    - cron: '0 */12 * * *'      # every 12h
  workflow_dispatch:           # manual â€œRun workflowâ€ button

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: rushela
          palette: github-dark
          output: output/github-contribution-grid-snake.svg

      - name: Commit SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'Rushela Ekanayaka'
          author_email: 'your.rushelbit17@gmail.com'
          message: 'chore: update snake animation'
          file_pattern: 'output/github-contribution-grid-snake.svg'
